// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGU3Yseiju2a92Gvv2uRWBJOLIrnQ4g3k',
    appId: '1:966832750162:web:fb7c8a853f09c23905a98b',
    messagingSenderId: '966832750162',
    projectId: 'fruits-valley-e242e',
    authDomain: 'fruits-valley-e242e.firebaseapp.com',
    storageBucket: 'fruits-valley-e242e.appspot.com',
    measurementId: 'G-ZV0HHF331D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfStkFaySFkJPIWwAq1CgMSKzK94E0Ymk',
    appId: '1:966832750162:ios:9b3beac8a4d2f77b05a98b',
    messagingSenderId: '966832750162',
    projectId: 'fruits-valley-e242e',
    storageBucket: 'fruits-valley-e242e.appspot.com',
    iosBundleId: 'com.example.fruitsValley',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfStkFaySFkJPIWwAq1CgMSKzK94E0Ymk',
    appId: '1:966832750162:ios:9b3beac8a4d2f77b05a98b',
    messagingSenderId: '966832750162',
    projectId: 'fruits-valley-e242e',
    storageBucket: 'fruits-valley-e242e.appspot.com',
    iosBundleId: 'com.example.fruitsValley',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmNKnEiaWaKqOdL6BEelCmT--1yRQxvrU',
    appId: '1:966832750162:android:50273f20ddfca12e05a98b',
    messagingSenderId: '966832750162',
    projectId: 'fruits-valley-e242e',
    storageBucket: 'fruits-valley-e242e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGU3Yseiju2a92Gvv2uRWBJOLIrnQ4g3k',
    appId: '1:966832750162:web:b80cafaacd120d0205a98b',
    messagingSenderId: '966832750162',
    projectId: 'fruits-valley-e242e',
    authDomain: 'fruits-valley-e242e.firebaseapp.com',
    storageBucket: 'fruits-valley-e242e.appspot.com',
    measurementId: 'G-XKFQ70PGZ4',
  );

}
